### Create bicycle
POST http://localhost:3000/bicycle
Content-Type: application/json

{
  "color":"rOSA",
  "gears": 12,
  "brand": "BMW",
  "modelo":"oFF-rOAD",
  "price": 1000
}


### Find All bicycle
GET http://localhost:3000/bicycle


### Find By Color

GET http://localhost:3000/bicycle/amarela

### Uptade Preço

PUT  http://localhost:3000/bicycle/4
Content-Type: application/json

{ 
  "price": 31000
}


### Find By Price

GET http://localhost:3000/bicycle/price/31000


### Sell

DELETE http://localhost:3000/bicycle/venda/5