### Create Bike
POST http://localhost:3000/bike
Content-Type: application/json

{
  "cor":"amarela",
  "marchas": 18,
  "marca": "Sundown",
  "modelo":"Lazer",
  "preco": 600
}


### Find All Bikes
GET http://localhost:3000/bike
