### Create Bike
POST http://localhost:3000/bike
Content-Type: application/json

{
  "color":"azul",
  "marchas": 18,
  "marca": "BMW",
  "modelo":"Estrada",
  "preco": 15000
}


### Find All Bikes
GET http://localhost:3000/bike


### Find By Color

GET http://localhost:3000/bike/amarela
